### ISSUE TITLE
Generate API v6.1

### ISSUE THREAD

**Issue by favoretti** [microsoft/azure-devops-go-api#114]
Hi,

Since one of the very interesting features of AzDO Pipeline Environments (Approvals and Checks) is available in 6.1 only (along with a few other goodies) - would it be possible to generate v6.1 as well?

Thanks,
Vladimir

**Comment by jholm117** [comment]
Any update on this? This is blocking the addition of approvals and checks to the terraform provider which we have a need for :)

**Comment by aristosvo** [comment]
@tedchamb Can we please get a new API version? :)

**Comment by nechvatalp** [comment]
There is a new version planned which would have all the APIs from 7.0 I can't provider any ETA at this time.

**Comment by nechvatalp** [comment]
Released new 7.1 version.
