### ISSUE TITLE
Generate API v7.1

### ISSUE THREAD

**Issue by aristosvo** [microsoft/azure-devops-go-api#123]
@nechvatalp Can we please have 7.1 generated?

I know it is still preview, but it seems the only way we could finally integrate [elastic pools](https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/elasticpools/create?view=azure-devops-rest-7.1) into automation like the Terraform Provider.

Open sourcing the process is also fine, as I can than easily setup a fork

Please vote on this issue: https://developercommunity.visualstudio.com/t/Update-of-the-Go-SDK-to-include-new-feat/10186787

**Comment by nechvatalp** [comment]
There is a new version planned which would have all the APIs from 7.0 I can't provider any ETA at this time.

**Comment by aristosvo** [comment]
@nechvatalp @tonybaloneyCan you please give an update about the ETA? Both this API and the [Python one](https://github.com/microsoft/azure-devops-python-api) (which would be our backup/second option) are really behind, making working with the Azure DevOps product from an automation perspective horrible.

**Comment by SSKLCP** [comment]
@nechvatalp please? 🥺

**Comment by nechvatalp** [comment]
Hi, unfortunately the plan to do a new release for either go/python has been shelved indefinitely. Sorry.

**Comment by nellyk** [comment]
@nechvatalp anyway i could help?

**Comment by hbuckle** [comment]
@nechvatalp 

This is basically condemning the Azure DevOps Terraform provider to death, can you share any more information about this decision?

**Comment by davidcorrigan714** [comment]
@nechvatalp  I noticed the other day that the Rust library uses the OpenAPI spec, which appears to be be current. Sounds like you all were using some custom generators in years past that are now lost or need some investment to revive, so maybe that's a low-cost way to keep them going. Has there been any consideration to releasing new versions of the Python & Go APIs based on that spec? Rebasing the Terraform provider on a new API structure would be a bit annoying, but probably still worth the one-time effort opposed to hacking in new features manually which we've started doing as the API is either stale or buggy.

**Comment by drewbren** [comment]
We've discussed as a team and will be able to prioritize a new version of the client next sprint, so we'll have it posted by the end of April. We are planning to adopt OpenAPI in the coming months and are considering how that may replace the need for these clients. For now, we're going to bring the clients current and then see what's possible with OpenAPI.

**Comment by davidcorrigan714** [comment]
Yayyy thanks @drewbren! We recently requested to be added to the new ["REST API support for connecting GitHub repositories (private preview)"](https://learn.microsoft.com/en-us/azure/devops/release-notes/2023/sprint-219-update#rest-api-support-for-connecting-github-repositories-private-preview) specifically to add it to the terraform provider so I don't have to re-add 50 repos to a connection every time we reset that PAT. I'll get it working in our fork one way or another but it'd certainly be nice to have it in the official client which will make upstreaming the new resource easier.

**Comment by nechvatalp** [comment]
New version 7.1 has been released, it should have all publicly available APIs that we have at this point.

**Comment by aristosvo** [comment]
Thanks @nechvatalp ! You've unlocked some cool automation possibilities for us, thanks a lot!
