### ISSUE TITLE
Generated SDK does not use interfaces, making testing difficult

### ISSUE THREAD

**Issue by nmiodice** [microsoft/azure-devops-go-api#21]
Its difficult to unit test against the generated SDK code (i.e., mocking the API response for a specific API call) because the factory used to generate the clients do not return an interface; instead they return a raw client.

This makes testing hard. Can the generated code be updated to (1) create an interface and (2) return the interface from the factory to create new clients?

**Comment by nmiodice** [comment]
@tedchamb Any updates and/or ETA on this

**Comment by tedchamb** [comment]
#22

**Comment by tedchamb** [comment]
@nmiodice , I have merged the changes in, please let me know if it does not meet your needs.
