### ISSUE TITLE
Avoid double JSON marshalling in UnmarshalCollectionJson

### ISSUE THREAD

**Issue by tmeckel** [microsoft/azure-devops-go-api#34]
`UnmarshalCollectionJson` uses a marshal/unmarshal strategy to return a strongly typed result from an REST API call that returns a collection like `/_apis/graph/groups`

https://github.com/microsoft/azure-devops-go-api/blob/47715c5e3aa127871321d18bb438712caa65dca9/azuredevops/client.go#L326

With employing the  GO reflect package, especially the [`StructOf`](https://golang.org/pkg/reflect/#StructOf) function, this marshal/unmarshal process could be replaced by a more concise and probably more performant solution.  With the help of `StructOf` the function can create a struct dynamically out of the required `value` attribute that has been passed as value (interface) type in parameter `v interface{}`)

##  Proposed fix

```go
func (client *Client) UnmarshalCollectionJson(jsonValue []byte, v interface{}) (err error) {
	t := reflect.TypeOf(v)
	if (t.Kind() == reflect.Ptr) {
	   t = t.Elem()
	} else {
	   return errors.New("value type must be a pointer")
	}
	sType := reflect.StructOf([]reflect.StructField{
		{Name: "Count", Type: reflect.TypeOf(0) },
		{Name: "Value", Type: t },
	})
	sv := reflect.New(sType)
	err = json.Unmarshal(jsonValue, sv.Interface())
	if err != nil {
	   return err
	}
	
	rv := reflect.ValueOf(v)
	rv.Elem().Set(sv.Elem().FieldByName("Value"))
	return nil
}
```

**Comment by tedchamb** [comment]
Thanks @tmeckel!  I appreciate the feedback.  I will look into it.

**Comment by tedchamb** [comment]
@tmeckel, thanks for your contribution!
