### ISSUE TITLE
GetWorkItems has a bug -  'definitions' in place of 'ids'

### ISSUE THREAD

**Issue by marcello-mirenda** [microsoft/azure-devops-go-api#38]
In this line https://github.com/microsoft/azure-devops-go-api/blob/59979e61bcc4eba58663cff5ae2aa120a9b84c35/azuredevops/workitemtracking/client.go#L2250

the code should be
`queryParams.Add("ids", listAsString)`

**Comment by tedchamb** [comment]
Thanks for reporting, I will take a look.

**Comment by tedchamb** [comment]
Fixed in #39
