### ISSUE TITLE
Provide sample code service endpoint azureRm

### ISSUE THREAD

**Issue by mikaelkrief** [microsoft/azure-devops-go-api#41]
Can you provide a sample code for create an Azure RM service point

**Comment by tedchamb** [comment]
Sorry Azure Resource Manager is not covered by this SDK.   This SDK is a wrapper around all the [Azure DevOps REST APIs](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.1).

**Comment by mikaelkrief** [comment]
Yes I know, I want to create a service connection in AzDo for Azure RM for use it in pipeline to deploy in Azure.

**Comment by tedchamb** [comment]
@mikaelkrief , have you looked at the REST documentation here:

https://docs.microsoft.com/en-us/rest/api/azure/devops/serviceendpoint/endpoints?view=azure-devops-rest-5.1

**Comment by mikaelkrief** [comment]
@tedchamb , but I will be interressed to have a sample for azurerm service end point, for implement in the Terraform AzureDevOps provider https://github.com/microsoft/terraform-provider-azuredevops
