### ISSUE TITLE
distributedtask/tasks is missing from API documentation and from taskagent.Client

### ISSUE THREAD

**Issue by exocom** [microsoft/azure-devops-go-api#42]
Hello, I'm currently working on the [microsoft/terraform-provider-azuredevops](https://github.com/microsoft/terraform-provider-azuredevops) plugin and I'm looking for a way to convert the name of a task into the taskId. 

Unfortunately the api, release.WorkflowTask.TaskId, requires a uuid and doesn't support using taskName in-lieu of uuid or a property taskName. I tested this with Postman to confirm. Ideally it would be great if the api supported taskName or taskId, however, the next best thing would be if  distributedtask/taks was added to this library allowing us to get all of the distributed tasks and then cache them. Then we can just convert the name to the id dynamically using a map.

After looking thru the code It does not appear possible to retrieve distributed tasks with this library. The Azure DevOps portal places a call to /_apis/distributedtask/tasks to retrieve a complete list of tasks and displays them in the side bar. I was hoping to use this library to get the same data. 

After some digging I also found that distributedtask/task  is not listed on the documentation site. I was expecting it to be under taskagent.Client, however, I only found distributedtask/taskGroups by following this [issue](https://github.com/MicrosoftDocs/vsts-docs/issues/412). Lastly also noticed the code for taskagent is autogenerated so I'm at a loss as to how to add this functionality, how does one contribute to this library?

Any suggestions? Any chance you can this to this library?

**Comment by exocom** [comment]
I was able to determine that the C# library already supports this endpoint via [GetTaskDefinitions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.teamfoundation.distributedtask.webapi.taskagenthttpclientbase.gettaskdefinitionasync?view=azure-devops-dotnet#Microsoft_TeamFoundation_DistributedTask_WebApi_TaskAgentHttpClientBase_GetTaskDefinitionAsync_System_Guid_System_String_System_Collections_Generic_IEnumerable_System_String__System_Nullable_System_Boolean__System_Object_System_Threading_CancellationToken_) and [GetTaskDefinitionsAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.teamfoundation.distributedtask.webapi.taskagenthttpclientbase.gettaskdefinitionsasync?view=azure-devops-dotnet#Microsoft_TeamFoundation_DistributedTask_WebApi_TaskAgentHttpClientBase_GetTaskDefinitionsAsync_System_Nullable_System_Guid__System_Collections_Generic_IEnumerable_System_String__System_Nullable_System_Boolean__System_Object_System_Threading_CancellationToken_)

See the [docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.teamfoundation.distributedtask.webapi.taskagenthttpclient?view=azure-devops-dotnet)

**Comment by tedchamb** [comment]
This is similar to the case in #43.  The owning team has attributed `GetTaskDefinitions` and `GetTaskDefinitionsAsync` as `[InternalUseOnly]`, which tells the client generator to skip these methods.  I will contact the team to see if they can shed some light on how customers should get the task id.

**Comment by tmeckel** [comment]
@tedchamb well it's kind of similar to my issue #43 ... it's not really similar because as @exocom mentioned the C# client implementation **does** support the function in question, where as the property `isDeleted` isn't available in the C# client library. So I think the tagging `[InternalUseOnly]` isn't honored by call client library maintainers 😁 and quite apart from that, I think it's an _odd_ design, that data which is available through an interface, is not exported in the client libraries. Either don't pass data at all, if it's considered private (internal) or pass data and make everything available to the caller.

**Comment by tedchamb** [comment]
The two c# methods are marked `[EditorBrowsable(EditorBrowsableState.Never)]`, so while they are technically in the C# client, they are hidden.   The c# documentation you are looking at was either generated before they were marked this way or there is a bug in the documentation generator.  Either way they have intentionally hidden these methods, which means there is a better way to get the same information.  I would recommend posting questions on the REST API documentation pages:

https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/?view=azure-devops-rest-5.1
