### ISSUE TITLE
Creating a new build definition with trigger

### ISSUE THREAD

**Issue by iRichLau** [microsoft/azure-devops-go-api#44]
With postman I am able to create a new build definition with a trigger with the following: 
""triggers": [
        {
            "branchFilters": [
                "+refs/heads/master"
            ],
            "pathFilters": "",
            "batchChanges": true,
            "maxConcurrentBuildsPerBranch": 1,
            "triggerType": "continuousIntegration"
        }
]"

But with the go api. I am using the CI struct: 

"type ContinuousIntegrationTrigger struct {
	// Indicates whether changes should be batched while another CI build is running.
	BatchChanges  *bool     `json:"batchChanges,omitempty"`
	BranchFilters *[]string `json:"branchFilters,omitempty"`
	// The maximum number of simultaneous CI builds that will run per branch.
	MaxConcurrentBuildsPerBranch *int      `json:"maxConcurrentBuildsPerBranch,omitempty"`
	PathFilters                  *[]string `json:"pathFilters,omitempty"`
	// The polling interval, in seconds.
	PollingInterval *int `json:"pollingInterval,omitempty"`
	// The ID of the job used to poll an external repository.
	PollingJobId       *uuid.UUID `json:"pollingJobId,omitempty"`
	SettingsSourceType *int       `json:"settingsSourceType,omitempty"`
}"

It won't create a trigger for me via the go api. I assume I am missing the triggerType from the payload because when I remove that from the postman payload it also won't work.

Is this some sort of defect that there is a missing "triggerType" field for the CI struct?

**Comment by iRichLau** [comment]
I can confirm that it is missing the triggerType field from the ContinuousIntegrationTrigger struct. With the current implementation it is impossible to create a Trigger as none of them have the triggerType field. I had to create my own Trigger struct and added the triggerType field for it to work.

**Comment by tedchamb** [comment]
@iRichLau , thanks for reporting this issue.  It has been fixed in PR #68, and is in the following release:

https://github.com/microsoft/azure-devops-go-api/releases/tag/azuredevops%2Fv5.1.0-b1
