### ISSUE TITLE
QueueBuild requires a non-nil Build even when sourceBuildId is specified

### ISSUE THREAD

**Issue by praneetloke** [microsoft/azure-devops-go-api#45]
Just as the title says, the function `Build.QueueBuild` requires a non-nil `Build` property in the `BuildArgs` parameter even when a non-nil `sourceBuildId` is specified. I can work around it by passing a pointer to an empty struct, but it shouldn't be needed.

As a side note, I don't know where to open this issue, but the Queue API doesn't seem to work at all. I always get an error response "item with the same key already exists" and when I go to the Azure Pipelines page, the new build shows up but is in some sort of a corrupted state.

**Comment by tedchamb** [comment]
@praneetloke , thanks for reporting these issues.  The `QueueBuild` operation performs a `POST` REST request.  `POST` requests require a body.  For `QueueBuild` the body is the `Build` property.  

See doc here: https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/queue?view=azure-devops-rest-5.1

You can make a report about the Queue API bug you found by filing an issue here:
https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds?view=azure-devops-rest-5.1
