### ISSUE TITLE
BUG: Unable to deserialize JSON to SecurityNamespaceDescription 

### ISSUE THREAD

**Issue by tmeckel** [microsoft/azure-devops-go-api#47]
Currently it's not possible to use the [Security Namespaces - Query](https://docs.microsoft.com/en-us/rest/api/azure/devops/security/security%20namespaces/query?view=azure-devops-rest-5.1) REST method, because the JSON deserializer isn't able to convert the received JSON structure into the corresponding GO struct `SecurityNamespaceDescription`.

An error is issued that the received `SeparatorValue` value can't be deserialized into an `int32` (`rune`)

![image](https://user-images.githubusercontent.com/14177833/72174061-28951480-33d9-11ea-9519-4e8f7c59ea54.png)

https://github.com/microsoft/azure-devops-go-api/blob/d4b68921f36257c573ed022d43faf146fc61f5cb/azuredevops/security/models.go#L107

According to the REST documentation the datatype for the `separatorValue` field is `string` and not `rune` (alias for `int32`).

![image](https://user-images.githubusercontent.com/14177833/72143490-12fefb00-3397-11ea-8fb1-d08f77b17022.png)

**Comment by tmeckel** [comment]
@tedchamb Would you be able to fix this bug in a timely manner, as my pull request to the Azure DevOps provider for management of security settings cannot be merged until this bug is fixed here!

https://github.com/microsoft/terraform-provider-azuredevops/pull/238

**Comment by tiwood** [comment]
@tedchamb, friendly reminder.

We have a few pull requests ready, which require this "bug" fixed.

**Comment by tedchamb** [comment]
@tmeckel, thanks for filing this issue, and thanks for your patience with the slow turn around on the fix.  The issue has been fixed by PR #64, and is available in the following release:

https://github.com/microsoft/azure-devops-go-api/releases/tag/azuredevops%2Fv5.1.0-b1

**Comment by tmeckel** [comment]
@tedchamb Awesome!! Many thanks having this nasty bug finally fixed!!!
