### ISSUE TITLE
It is not possible to use custom HTTP client with requests to Azure Devops

### ISSUE THREAD

**Issue by ligurio** [microsoft/azure-devops-go-api#52]
I'm using Azure Golang SDK and want to use custom HTTP client to access to Azure Devops.
As far as I understand it is not possible now. Please provide such ability.

**Comment by tedchamb** [comment]
@ligurio , can you provide more detail on what you are trying to do?

**Comment by ligurio** [comment]
@tedchamb I'm trying to access to hosted Azure Devops instance with custom SSL certificates. I don't know how to explain in terms of security. Probably my company uses their own SSL PKI and internal sites uses certificates from it.

**Comment by pec1985** [comment]
+1

**Comment by tmeckel** [comment]
I filed a pull request #49 long ago which could easily be expanded to have the ability to set configuration options on the HTTP client.

**Comment by artbegolli** [comment]
@tmeckel So I've looked at adding options to enable you to use a custom http client as well as retry based on your implementation. 

My conern is that to allow a user to set custom settings or options with `NewClientWithOptions` function all the auto-generated clients (e.g. git, build, core etc.) must also support the ability to pass in options. 

The actual call to NewClient is nested through a few different funcs. @tedchamb, could you share some light into how and where these clients are generated from so I can take a crack at allowing users to specify custom options in all clients?

**Comment by artbegolli** [comment]
PR #78

**Comment by joyciep** [comment]
Any updates here? We also need custom HTTP clients

**Comment by michalg9** [comment]
Any updates here? Seems quite some people are requesting this. There was a PR from @artbegolli making it possible to use custom http client (https://github.com/microsoft/azure-devops-go-api/pull/78) - it seems to be an extension of PR from @tmeckel (https://github.com/microsoft/azure-devops-go-api/pull/49) (thanks guys! 🙌). However, both of those PRs are closed and seem not to be included in the main release. Any news on it @tedchamb ? 🙏

**Comment by c-brooks** [comment]
Hello 👋 I've opened a pull request for a simple way to supply a custom HTTP Client in https://github.com/microsoft/azure-devops-go-api/pull/103. That PR should close this issue.

**Comment by tmeckel** [comment]
@c-brooks good luck ... I closed my PR #49 here because the repo is definitely abandoned and does not get the care it deserves from Microsoft. So many issues have piled up here that it's kinda ridiculous.
