### ISSUE TITLE
Missing fields on git.IdentityRefWithVote

### ISSUE THREAD

**Issue by bvwells** [microsoft/azure-devops-go-api#53]
The model git.IdentityRefWithVote defined here

https://github.com/microsoft/azure-devops-go-api/blob/3cd87c562d09a2ef1ea84ed42e659cec59c4f2a1/azuredevops/git/models.go#L2296

is missing various fields. For reference,

https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20request%20reviewers/create%20pull%20request%20reviewer?view=azure-devops-rest-5.1#identityrefwithvote

It would be great if the models could be updated to add these missing fields.

**Comment by bvwells** [comment]
Was thinking of raising a PR, but I guess https://github.com/microsoft/azure-devops-go-api/blob/dev/azuredevops/git/models.go is auto-generated...

**Comment by tedchamb** [comment]
Yeah the model code is auto-generated, so any fix needs to be made on the code generator.  I'll have a look when I get a chance.

**Comment by tmeckel** [comment]
@tedchamb same with my bug #47 would be great if you could fix that at the same time

**Comment by tedchamb** [comment]
@bvwells , thanks for reporting this issue. It has been fixed in PR #66, and is in the following release:

https://github.com/microsoft/azure-devops-go-api/releases/tag/azuredevops%2Fv5.1.0-b1

**Comment by bvwells** [comment]
Thanks, I'll give it a go. I suspect the v5 tag will cause an issue as the go module is not defined as v5...

**Comment by tedchamb** [comment]
@bvwells , thanks for the heads up on the v5 issue.  I will fix this. Still not used to all the go module rules.

**Comment by tedchamb** [comment]
I added a new release under v1, while i fix the v5 issue:
https://github.com/microsoft/azure-devops-go-api/releases/tag/azuredevops%2Fv1.0.0-b2

**Comment by bvwells** [comment]
Thanks @tedchamb!
