### ISSUE TITLE
response should include response code

### ISSUE THREAD

**Issue by xuzhang3** [microsoft/azure-devops-go-api#54]
When I get the response from backend service, the HTTP status code does not exist. I don't know if the resource does not exist or the service is unavailable. 
As client , different HTTP status code will show different behaviors.

**Comment by tedchamb** [comment]
If the rest call returns an error, It will typically be a [`WrappedError`](https://github.com/microsoft/azure-devops-go-api/blob/3cd87c562d09a2ef1ea84ed42e659cec59c4f2a1/azuredevops/models.go#L110), which contains the status code.  If it's not a `WrappedError`, then it will be one of a few other types of errors that should contain more information about what the issue is.  Other Error types are contained in that same file.

**Comment by xuzhang3** [comment]
> If the rest call returns an error, It will typically be a [`WrappedError`](https://github.com/microsoft/azure-devops-go-api/blob/3cd87c562d09a2ef1ea84ed42e659cec59c4f2a1/azuredevops/models.go#L110), which contains the status code. If it's not a `WrappedError`, then it will be one of a few other types of errors that should contain more information about what the issue is. Other Error types are contained in that same file.

The  ```WrappedError.ErrorCode```  here seems can solve my problem,  where can I find the ```ErrorCode``` definition.  In my scenario, I got returned ```WrappedError``` with error message ```Identity not found with``` and ```ErrorCode=0```, but I'm not sure if ```ErrorCode=0``` represent resource not found.

**Comment by tedchamb** [comment]
`ErrorCode=0` means there was no error code reported.   Take a look at the Status Code if it was set.
Not all exceptions set all values.

**Comment by mybayern1974** [comment]
hi @tedchamb , I'm in the same engineering team with xuzhang3. I'd like to clarify our contexts to serve you better possibly help us: From ADO Go API response here, **_we need to programmatically distinguish ado-resource-not-exist from other error situations and normal  situations_**. Generally we expect to receive 404 but right now seems the current implementation is not like that. So could you please tell us a programmatical rule that exactly tells "your wanted resource does not exist"? Take the above discussion as example, may we assume that once we receive "Identity not found with" in the returned error msg, then we can regard it means resource does not exist? If so, can this rule cover all "resource-not-found" scenarios in ADO?

To clarify contexts at our side a little bit: If we can not do **_this above_**, we would be blocked per the required onboarding check list [here](https://github.com/microsoft/terraform-provider-azuredevops/issues/241): 

> _...If a resource cannot be found(404) in the READ function, we should do a d.SetId("") to remove it from the statefile..._

Thank you tedchamp for your help in advance!

**Comment by nmiodice** [comment]
Is it the case that we should be using the `StatusCode` field? https://github.com/microsoft/azure-devops-go-api/blob/3cd87c562d09a2ef1ea84ed42e659cec59c4f2a1/azuredevops/models.go#L119

**Comment by xuzhang3** [comment]
> Is it the case that we should be using the `StatusCode` field?
> 
> https://github.com/microsoft/azure-devops-go-api/blob/3cd87c562d09a2ef1ea84ed42e659cec59c4f2a1/azuredevops/models.go#L119

It  would be better if the status code is returned, otherwise if Ted can provide the definition of ```ErrorCode``` and ```StatusCode``` defined in ```WrapperError```  we can also solve this problem.

**Comment by tedchamb** [comment]
Sorry for the slow reply, I have a new job, and have been busy ramping up there.  The `ErrorCode` is a unique number for the specific error that makes it easier for users to do a web search to look up the issue.  `StatusCode` is meant to be the actual http status code.  Currently we are only setting it in some conditions.  It looks like we need to also set it here:

https://github.com/microsoft/azure-devops-go-api/blob/17093eb5e360594433f48dbc73a40889c521fc59/azuredevops/client.go#L382

by changing:
```
	var wrappedError WrappedError
	err = json.Unmarshal(body, &wrappedError)
	if err != nil {
		return err
	}
```

to something like this:

```
	var wrappedError WrappedError
	err = json.Unmarshal(body, &wrappedError)
        wrappedError.StatusCode = response.StatusCode
	if err != nil {
		return err
	}
```

If you test this out, you can either submit a PR, or I can make the change and get in there.
