### ISSUE TITLE
Create Push API body has missing GitChange struct in Golang documentation

### ISSUE THREAD

**Issue by siddharthprakash01** [microsoft/azure-devops-go-api#57]
Docs: https://godoc.org/github.com/microsoft/azure-devops-go-api/azuredevops/git#GitCommitRef
POST https://dev.azure.com/{organization}/{project}/_apis/git/repositories/{repositoryId}/pushes?api-version=5.1
The Create Push API above has GitCommitRef as one of the structs to pass in request body. 
The documentation mentions GitChange as one of the fields in GitCommitRef.
However, in the go docs, GitCommitRef takes an interface instead of GitChange.

**Comment by tedchamb** [comment]
@siddharthprakash01 , thanks for filing this issue.  It has been fixed in PR #68, and is in the following release:

https://github.com/microsoft/azure-devops-go-api/releases/tag/azuredevops%2Fv5.1.0-b1
