### ISSUE TITLE
Unable to create KeyVault backed variable group due to typing issues

### ISSUE THREAD

**Issue by nmiodice** [microsoft/azure-devops-go-api#58]
When creating a KeyVault, we need to work with the [following struct](https://github.com/microsoft/azure-devops-go-api/blob/543de4815ec27be371a10b39b6750005d6c34a6c/azuredevops/taskagent/models.go#L2480-L2503). I'm showing an abridged version here:

```go
type VariableGroup struct {
	Name *string
	ProviderData *VariableGroupProviderData
	Variables *map[string]VariableValue
}
```

For most variable groups there is no problem. However, when creating a KeyVault backed variable group, the strict typing can become a challenge. There are 2 issues:
- `VariableGroup.ProviderData` needs to be configured as a [`*AzureKeyVaultVariableGroupProviderData`](https://github.com/microsoft/azure-devops-go-api/blob/543de4815ec27be371a10b39b6750005d6c34a6c/azuredevops/taskagent/models.go#L137-L141)
- `Variables` needs to be configured as a [`*map[string]AzureKeyVaultVariableValue`](https://github.com/microsoft/azure-devops-go-api/blob/543de4815ec27be371a10b39b6750005d6c34a6c/azuredevops/taskagent/models.go#L143-L149)

The lack of inheritence in Go requires the generated code to produce a `VariableGroup` that looks more like the following:
```go
type VariableGroup struct {
	Name *string
	ProviderData interface{} // Maybe  pointer? Not sure...
	Variables map[string]interface{}  // Maybe  pointer? Not sure...
}
```

**Note**: We will need to be able to have this data in `POST` API calls as well as returned by the `GET` API call.

**Comment by nmiodice** [comment]
cc @EliiseS

**Comment by nmiodice** [comment]
Related issue in developercommunity.visualstudio

https://developercommunity.visualstudio.com/content/problem/1009010/-go-sdk-unable-to-create-keyvault-backed-variable.html

**Comment by tedchamb** [comment]
Fixed in this release:
https://github.com/microsoft/azure-devops-go-api/releases/tag/azuredevops%2Fv1.0.0-b3
