### ISSUE TITLE
Unable to add proxy settings while creating New Client

### ISSUE THREAD

**Issue by siddharthprakash01** [microsoft/azure-devops-go-api#61]
There is no way to add proxy url settings in NewClient function.
https://pkg.go.dev/github.com/microsoft/azure-devops-go-api/azuredevops/?tab=doc#NewClient

**Comment by tedchamb** [comment]
Here is an example of how you can set a proxy:

```
os.Setenv("HTTP_PROXY", "http://localhost.:8888")
```

**Comment by siddharthprakash01** [comment]
os.Setenv applies for all APIs in the project.
I have attempted to exclude other APIs by adding os.Setenv("NO_PROXY", "url1,url2,url3").
Is it possible to set only for Azure client ?
