### ISSUE TITLE
Incorrect value for azuredevops.Time in query parameter

### ISSUE THREAD

**Issue by bcho** [microsoft/azure-devops-go-api#80]
Hi we found that in [api: `BuildClient.GetBuilds`](https://github.com/microsoft/azure-devops-go-api/blob/0eaf2fc4ab76634f0b91a6c48494ad237e34e32e/azuredevops/build/client.go#L1527), the time value in parameter is incorrect:

```
map[definitions:[the-pipeline-id] minTime:[2020-08-03 11:11:36.300224 +0800 CST m=-10797.832509577] queryOrder:[queueTimeAscending]]
```

expected value should be formatted with RFC3339:

```
map[definitions:[the-pipeline-id] minTime:[2020-08-03T11:11:36+08:00] queryOrder:[queueTimeAscending]]
```

**Comment by bcho** [comment]
Also found multiple places which usage like:

```
XXXTime).String()
```

I propose we add a new method call `AsQueryParameter()` to `auzredevops.Time` and convert usages like this to this new method.  @tedchamb  What do you think?

**Comment by tedchamb** [comment]
#89

**Comment by tedchamb** [comment]
https://github.com/microsoft/azure-devops-go-api/releases/tag/azuredevops%2Fv1.0.0-b5

**Comment by carolwu-1206** [comment]
The same issue is in v6, should anyone fix it?
