### ISSUE TITLE
[feature] Add new taskagent resource functionality

### ISSUE THREAD

**Issue by aleqsss** [microsoft/azure-devops-go-api#90]
It seems like the azure-devops-go-api doesn't support [TaskAgentPoolOptions](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/pools/add?view=azure-devops-rest-6.0#taskagentpooloptions), from version 6.0 and ongoing, of the Azure DevOps REST API.

As of my understanding, the azure-devops-go-api is using an internal tool/code generator ([genclient](https://dev.azure.com/mseng/AzureDevOps/_wiki/wikis/AzureDevOps.wiki/2729/Rest-Client-Generation)), hence I can't make a pull request and add the functionality manually. So I guess this will be a feature request.

It would be of great use, if you could add support for the new elastic pool (TaskAgentPool backed by the Elastic pool service) functionality of Azure DevOps (and all other new Task Agent resource functionality for that matter), to the [taskagent](https://github.com/microsoft/azure-devops-go-api/tree/dev/azuredevops/taskagent), or where you consider would be most suitable.

**Comment by aleqsss** [comment]
@tedchamb what do you say about this? 🙂

**Comment by aleqsss** [comment]
@xuzhang3 what do you say about this (in connection with https://github.com/microsoft/terraform-provider-azuredevops/issues/204) 🙂

**Comment by simongottschlag** [comment]
@aleqsss I don't think we'll be getting updates for the Golang SDK anytime soon. I've already given up.

Maybe time to write our own, like they've done at Hashicorp for other Azure services?

MS Graph: https://github.com/manicminer/hamilton
Azure Storage: https://github.com/tombuildsstuff/giovanni

**Comment by aleqsss** [comment]
Perhaps @simongottschlag, but at least we've gotten information inside of [#204](https://github.com/microsoft/terraform-provider-azuredevops/issues/204), "that v6.x will be released but do not have the timeline".

**Comment by aleqsss** [comment]
Closing this feature request since [Version 6.0.0](https://github.com/microsoft/azure-devops-go-api/releases/tag/azuredevops%2Fv6.0.0) and even [ Version 7.1.0](https://github.com/microsoft/azure-devops-go-api/releases/tag/azuredevops%2Fv7.1.0) are now supported. 👍
