### ISSUE TITLE
GetAllWikis 401

### ISSUE THREAD

**Issue by yene** [microsoft/azure-devops-go-api#95]
```
wikiClient, err := wiki.NewClient(ctx, connection)
response, err := wikiClient.GetAllWikis(ctx, wiki.GetAllWikisArgs{})
```
gives me a 401 but the other APIS GetRepositories and GetProjects work.
What am I missing here?

**Comment by nmiodice** [comment]
Does your personal access token have the `wiki::read` permission?

![image](https://user-images.githubusercontent.com/2497673/106304119-3140ce80-6218-11eb-82fe-19be206e0ee3.png)

**Comment by yene** [comment]
Thanks I will try, I thought it was a subset of the Git permissions.
